### ISSUE TITLE
Confusion during training IDCN

### ISSUE THREAD

**Issue by sachinpuranik99** [zhenngbolun/S-Net#6]
In the IDCN training code file `code/IDCN.py` I see that the model IDCN uses output_list as the target, which is of length 9. But the `y` tensor that's provided during training is a list of length 1.
Is this intended?

**Comment by zhenngbolun** [comment]
This is because we want to study the internal outputs of the network. You can ignore this and directly output the tensor y in both training phase and testing phase.

**Comment by sachinpuranik99** [comment]
Thanks. Is it possible to upload the IDCN pre-trained model to onedrive? I don't have a pan baidu account.

**Comment by zhenngbolun** [comment]
Well, the uploading speed is extremely slow.
Please tell us the models you need, and we will upload them later.
However, we still suggest you to download the models from the pan baidu.

**Comment by zhenngbolun** [comment]
Or, you can send the testing images to us, and then we sendback the testing results to you.

**Comment by sachinpuranik99** [comment]
> However, we still suggest you to download the models from the pan baidu.

@zhenngbolun I don't have a Baidu account, I couldn't create one without a china mainland phone number, so downloading from baidu is not an option. 

>Please tell us the models you need, and we will upload them later.

I am looking for all the checkpoints of IDCN and IDCN_f. 

>Or, you can send the testing images to us, and then we sendback the testing results to you.

I have a lot of images(more than 500). Sending PNGs back and forth would cost you more data than re-uploading the model files.

If not onedrive, can you try gdrive, git lfs or any other file-sharing website(zippyshare, dropbox)?
